version: '2'

services:
  web:
    build: .
    container_name: habit_tracker
    command: npm run dev-server
    volumes:
      - ./:/code
    ports:
      - "8080:8080"
    networks:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=password

  # db:
  #   container_name: habit_tracker_db
  #   image: mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #   networks:
  #     - db

networks:
  db:
