web:
  container_name: web
  image: digitallyseamless/bottle
  command: python3 /code/app.py --reload
  links:
    - db
  ports:
    - "8080:8080"
  volumes:
    - ./:/code
  environment:
    - MYSQL_ROOT_PASSWORD=password

db:
  container_name: db
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=password
